
MyService:
  text: "hello"

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: "microservices"

mcode:
  token:
    secret: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize"
    expiration: "28800"